spring.application.name = backend

server.port = 8080

# Establishes the location & behaviors of the database
spring.datasource.url=jdbc:sqlite:source/main/resources/database/smarthome.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.platform=sqlite



