spring.application.name = backend

server.port = 8080

# Establishes the location of the database
spring.datasource.url=jdbc:sqlite:../data/smarthome.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Determines Hibernates Behaviors
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.sql.init.mode=never
spring.sql.init.platform=sqlite

logging.level.org.springframework.web=info


spring.mvc.problemdetails.enabled=true
logging.file.name=../data/error.log




