spring.application.name = backend

server.port = 8080

# Establishes the location & behaviors of the database
spring.datasource.url=jdbc:sqlite:C:/Users/copel/Documents/College/OODesign/smart-home/backend/data/mydb.sqlite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.platform=sqlite



